In [19]:
def test():
   print("test() for function")
   return
test()

test() for function


In [20]:
def test():
   print('test() for function ')
   return
test()

test() for function 


In [21]:
class Demo:
   def test(self):
       print("test() for the class and method")
       return
obj = Demo()
obj.test()

test() for the class and method


In [22]:
class Demo1:
   def fact(self,n):
       #return the factorial
       fact = 1
       while(n!=0):
           fact = fact * n
           n = n-1
       return fact
p1 = Demo1()
print(p1.fact(5))

120


In [24]:
class Demo2:
   def __init__(self,p1,p2):
       self.p1= p1
       self.p2= p2
       
   def add(self,p1,p2):
        return p1 + p2
   
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [25]:
class person(object):
   def __init__(self,name):
       self.name=name
   def getname(self):
       return self.name
   def isemployee(self):
       return False
class employee(person):
   def isemployee(self):
       return True
emp=person("anil")
print(emp.getname(),emp.isemployee())
emp1=person("akhil")
print(emp1.getname(),emp1.isemployee())
lst=[1,2,3,4]
print(lst)                                                         

anil False
akhil False
[1, 2, 3, 4]


In [26]:
             import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)                                

[1 2 3 4]


In [27]:
                  lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [28]:
lst = [1.0,2.5,3.6,9.5]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [29]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)


(4,)
float64


In [30]:
a1=np.array([(1,2,3),(4,5,6,)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)
# re-shape the given array
#numby.reshape(array)name,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

(2, 3)
(3, 2)
[[1 2 3]
 [4 5 6]]


In [31]:
a1=np.array([(1,2,3),(4,5,6,)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)
# re-shape the given array
#numby.reshape(array)name,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

(2, 3)
(3, 2)
[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
a1=np.array([(1,2,3),(4,5,6,)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

(2, 3)
(3, 2)
[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
#append some data ----horizontally
#append some data------vertically
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [35]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))


[[1 2 3 4 5 6]]


In [37]:
print(thokkalo python)
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))
print(kodi tan)

SyntaxError: invalid syntax (<ipython-input-37-ea3c4a1f706e>, line 1)

In [38]:
a1=np.random.normal(5,0.5,10)
print(a1)

[4.28231161 4.96737527 4.52511453 4.08100868 4.95776295 4.8937607
 4.67697212 5.47961386 4.60438807 4.97351795]


In [41]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [42]:
np.zeros((2,2))
np.zeros((2,2),dtype=np.int64)
np.ones((4,3),dtype=np.int64)
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=4
np.asarray(A)[3][3]=16
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]
[[ 1  1  1  1]
 [ 1  1  1  4]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [44]:
import numpy as np
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [46]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [47]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [48]:
 a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [49]:
a2=np.array([(1,2,3),(4,5,6)])
print("second row:",a2[1])


second row: [4 5 6]


In [50]:
a1=np.array([(1,2,3),(4,5,6,)])
print("second column:",a1[:,2])


second column: [3 6]


In [51]:
a1=np.array([(1,2,3),(4,5,6,)])
print("silicing row:",a1[1])


silicing row: [4 5 6]


In [52]:
a1=np.array([(1,2,3),(4,5,6)])
print("silcing column:",a1[:,2])

silcing column: [3 6]


In [53]:
a1=np.array([(1,2,3),(4,5,6)])
print("silcing row:",a1[:,1])

silcing row: [2 5]


In [54]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))


[4.42135791 4.59230602 4.29128427 5.37158189 3.63107573 5.19830866
 3.87617415 4.27585685 5.06734849 5.01138549]
Min value= 3.6310757295457377
Max value= 5.371581885114983
Mean value= 4.573667944718096
Median value= 4.506831965853224


In [55]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [56]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [ ]:
import pandas as pd
dict = ()